### ISSUE TITLE
Update Maximo Application Suite to use CA Issuer

### ISSUE THREAD

**Issue by smatthyssen** [cloud-native-toolkit/software-everywhere#102]
Requirement for MAS Core release is manual instructions

**Comment by triceam** [comment]
Initial focus is validate/update what's in our docs.
Adding automation for this will come later (outside of this epic).

**Comment by tcskill** [comment]
closed with: https://github.com/cloud-native-toolkit/terraform-gitops-cp-maximo/pull/20
