### ISSUE TITLE
Tammy would like a module to provision the managed DB2 Warehouse instance on IBM Cloud

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#128]

**Comment by RamyaRaghuveera** [comment]
This can be mostly done by enhancing the existing db2 module(https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2) by passing a different value(db2wh) to the `db2instancetype ` variable.Test stages/prereqs for the module would need to be changed. This is based on the info shared by product team and is not currently tested: https://ibm-cloudplatform.slack.com/archives/C019EJ0QH4Y/p1649683303090389, https://github.ibm.com/ibm-privatecloud-databases/provisioning/blob/develop/provisioning.md
