### ISSUE TITLE
Request access: {Sarang/Dinesh/Dileep} New ROKS Cluster with Portworx for cp4ba(Business Automation)

### ISSUE THREAD

**Issue by saratrip** [cloud-native-toolkit/software-everywhere#144]
**Email address**
@saratrip @dineshchandrapandey @DileepPaul ,brahm.singh@ibm.com , mverma17@in.ibm.com

**Cloud environment**
IBM Cloud account, 

**Purpose**
Request to create new ROKS Cluster with Portworx for cp4ba(Business Automation). We are using OCP48 gitops cluster but are unable to do test on the cluster because the common service operator is giving issues/not installed. We are unable to proceed and it is major blocker for us.

**Duration of access**
3 Months
![image (5)](https://user-images.githubusercontent.com/34574383/164152382-cbdbe07c-5af8-4373-8740-448892326924.png)

**Comment by triceam** [comment]
Cluster provisioned in the Cloud Native Squad account:
https://cloud.ibm.com/kubernetes/clusters/ca5sc78w0suepvumiqn0/overview?platformType=openshift&region=us-east&resourceGroup=2895876252b04bcb8af608662e0ad20b

Portworx deployed & ArgoCD installed.

OpenShift UI available at: https://console-openshift-console.toolkit-dev-cp4ba-2ab66b053c14936810608de9a1deac9c-0000.us-east.containers.appdomain.cloud/dashboards

Configured for the `ocp4_latest_gitops_cp4ba` test profile:
https://github.com/cloud-native-toolkit/action-module-verify/tree/main/env/ocp4_latest_gitops_cp4ba
