### ISSUE TITLE
CP4D - DB2 - Warehouse BOM

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#160]
Create the BOM for the CP4D - DB2 - Warehouse that includes all the modules required for creating DB2W

**Business Value:**

If customer wants to install the DB2 Warehouse which becomes easy to install components that are related to DB2 Warehouse.

**Comment by balasgit** [comment]
Working on db2 WH BOM

**Comment by smatthyssen** [comment]
using Docker, was blocked by Colima last week

**Comment by balasgit** [comment]
Currently blocked by the modules not getting published to catalog https://ibm-cloud.slack.com/archives/C02KB99P2JC/p1654961418665239

**Comment by balasgit** [comment]
Blocked by this issue - https://github.com/cloud-native-toolkit/software-everywhere/issues/267

**Comment by balasgit** [comment]
terraform destroy causing issues - https://github.com/cloud-native-toolkit/software-everywhere/issues/264
