### ISSUE TITLE
CP4D - Namespace Strategy (Single Vs Multiple )

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#177]
**as per CP4D prod docs,** 
  - Installing on the single namespace with all the CP4D Base / Foundation / Zen along with DB2 seems to be straight forward approach as Pros. 
 - Exploring how to install on multiple namespaces (Pros / Cons)

**Comment by triceam** [comment]
Closing, this is covered by:
- [CP4D Express Installation](https://github.com/cloud-native-toolkit/software-everywhere/issues/190)
- [CP4D Specialized Installation](https://github.com/cloud-native-toolkit/software-everywhere/issues/177)
