### ISSUE TITLE
CP4D support specialized installation

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#191]
We switched CP4D to use the express installation instead of specialized installation per: https://github.com/cloud-native-toolkit/software-everywhere/issues/190

This was a temporary solution, and we should implement support for the specialized installation (spanning multiple namespaces), as [OpenShift best practices recommend to isolate workloads in their own namespace](https://cloud.redhat.com/blog/openshift-runtime-security-best-practices), instead of having everything deployed in a single namespace.  Our original installation implementation was using the specialized installation method, and we need to bring it back with full support.

**Comment by triceam** [comment]
Perhaps we can make this a installation option... the user can choose whether they want express or specialized installation.

**Comment by balasgit** [comment]
Supported specialization installation and published artifacts
