### ISSUE TITLE
Request to create a new Cluster for CP4D testing

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/software-everywhere#199]
We need new Cluster for CP4D testing.
We tested gitops-cp4d-instance module using our Data Squad test cluster and works fine with our changes ( https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-instance/issues/9 and https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-instance/issues/11)

The old cluster (toolkit-dev-cp4d) is having issues with ArgoCD setup. 
Throwing these error in Actions,

**Error: local-exec provisioner error
│
│  with module.gitops_ibm_catalogs.module.pull_secret.module.seal_secrets.null_resource.seal_secrets,
│  on .terraform/modules/gitops_ibm_catalogs.pull_secret.seal_secrets/main.tf line 14, in resource “null_resource” “seal_secrets”:
│  14: provisioner “local-exec” {**

**Comment by triceam** [comment]
We need to figure out which module's tests keeps overwriting sealed-secrets.  I just rebuilt this cluster a few days ago

**Comment by triceam** [comment]
I was able to execute actions *without* encountering the sealed-secrets error that was reported.  I still rebuilt the cluster anyway b/c I was seeing other odd behavior on it.
