### ISSUE TITLE
Maximo test environments

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#201]
Need clusters for testing Maximo
- [x] ROKS
- [x] AWS
- [x] Azure
- [ ] Delete all other maximo clusters on all clouds.

These clusters cannot be used for anything else!
Clusters should be based on templates

**Comment by triceam** [comment]
**big enough for maximo
- 16x64
- 3 or more workers
- portworx storage

**Comment by triceam** [comment]
ROKS Environment:
- [`maximo-ocp48`](https://cloud.ibm.com/kubernetes/clusters/c9t8pljw017f2bjc7tqg/overview?region=us-east&resourceGroup=2895876252b04bcb8af608662e0ad20b)
- https://console-openshift-console.maximo-ocp48-2ab66b053c14936810608de9a1deac9c-0000.us-east.containers.appdomain.cloud/
- 4 Nodes (16x64)
- Portworx deployed
- IBM ID Authentication

**Comment by triceam** [comment]
ARO Cluster:

- [`maximo-aro`](https://portal.azure.com/#@ibm.onmicrosoft.com/resource/subscriptions/bc1627c6-ec80-4da3-8d18-03e91330e2f1/resourceGroups/maximo-testing/providers/Microsoft.RedHatOpenShift/OpenShiftClusters/maximo-aro/dxresourceid)
- https://console-openshift-console.apps.kbbupt1f.eastus.aroapp.io/
- `worker_count: 3`
- Portworx deployed
- integrated with GHE auth

**Comment by triceam** [comment]
ROSA Cluster:
- [`maximo-rosa`](https://console.redhat.com/openshift/details/s/297BIe9QTZbyTBfh2wsDllC40ir)
- [AWS EC2 Resources](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#Instances:v=3;instanceState=running;search=:maximo)
- https://console-openshift-console.apps.maximo-rosa.r47m.p1.openshiftapps.com/
- GHE authentication
- Portworx deployed

**Comment by triceam** [comment]
- The ROKS cluster was created manually, and used the [IBM portworx bom](https://github.com/cloud-native-toolkit/automation-solutions/blob/main/boms/infrastructure/ibmcloud/_common/storage/210-ibm-portworx-storage.yaml) for the portworx deployment.
- The ARO cluster was created from our [Ansible quickstart](https://github.com/cloud-native-toolkit/ansible-azure-infra-openshift), and the [Azure portworx bom](https://github.com/cloud-native-toolkit/automation-solutions/blob/main/boms/infrastructure/azure/_common/storage/210-azure-portworx-storage.yaml) was used for deployment. 
- The ROSA cluster was created from [ROSA getting started guide](https://docs.openshift.com/rosa/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.html), and portworx deployed using the [AWS Portworx bom](https://github.com/cloud-native-toolkit/automation-solutions/blob/main/boms/infrastructure/aws/_common/storage/210-aws-portworx-storage.yaml).

**Comment by amkanjil** [comment]
Facing login issues with ROSA and ARO clusters, kindly help with the credentials to be used
<img width="1440" alt="Screenshot 2022-05-16 at 5 08 24 PM" src="https://user-images.githubusercontent.com/85481349/168584737-cc3b900d-29b0-4b9a-9119-c97200a4c3e3.png">
<img width="1440" alt="Screenshot 2022-05-16 at 5 07 42 PM" src="https://user-images.githubusercontent.com/85481349/168584740-f2f21dd4-e94b-468a-ad0e-9de0e2fddd07.png">
.

**Comment by triceam** [comment]
As I mentioned on slack and in the thread above, use Github Enterprise (GHE) authentication...

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/974294/168591850-e3bf8ad9-aa49-4ae3-9978-b781f88a70a5.png">

**Comment by amkanjil** [comment]
Hi Andrew,
That is exactly what I tried and got the error for the ARO cluster. Is there some specific access I'm required to have?
For the ROSA cluster however, that option doesn't even show up.

**Comment by triceam** [comment]
It authenticates using the GHE `gs-labs/software-everywhere` team. 

Did you attempt resetting the credentials using the `rosa` cli on the rosa cluster?  The configuration has been completely wiped and is no longer on the cluster, so I have to reconfigure it.

**Comment by triceam** [comment]
I just added you to the `gsi-labs/software-everywhere` team, so you should have access now.

**Comment by amkanjil** [comment]
My GHE ID is amkanjil.
I haven't touched the ROSA cluster, wasn't able to login the first time I tried.

**Comment by triceam** [comment]
Oauth has been restored on the ROSA cluster

**Comment by amkanjil** [comment]
I'm able to login to the ARO cluster now. Thanks for the access.
The ROSA cluster still shows up as follows:
<img width="1440" alt="Screenshot 2022-05-16 at 7 16 57 PM" src="https://user-images.githubusercontent.com/85481349/168607407-4f3524bd-b6c9-4d13-81bc-d714b89dd57b.png">

**Comment by triceam** [comment]
Weird... its gone again.   Let me look into it.

**Comment by triceam** [comment]
Attempting to configure Oauth using the `rosa` cli, but it is not showing up...

<img width="912" alt="image" src="https://user-images.githubusercontent.com/974294/168611271-c21ee475-f3b5-41c6-af0a-fc95456a5a4e.png">

Still showing no ghe login option:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/974294/168611426-0b8180bf-a0fd-482e-8260-179e4bdb7de9.png">

**Comment by triceam** [comment]
It's back.  Let's see if it stays... 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/974294/168618716-9c8ef8e2-7c27-4610-a84f-a1a65e43fc48.png">

**Comment by amkanjil** [comment]
Looks like it's working now. Thanks Andrew.

**Comment by mjperrins** [comment]
Where are the IPI Clusters ?

**Comment by triceam** [comment]
@mjperrins There is an IPI cluster here provisioned by @noe:
https://console-openshift-console.apps.ocp-48-maximo.clusters.azure.ibm-software-everywhere.dev/ 
However that was not created as part of this request.  

We have not released automation for IPI clusters for AWS or Azure yet, so I used ROSA for AWS and @rich-ehrhardt's  ansible quick start for Azure.

**Comment by amkanjil** [comment]
@triceam The ROKS cluster needs to be cleaned up for retesting of the latest BOM. Terraform destroy or detroy-all.sh didn't work for me. Can you please take a look at it?
