### ISSUE TITLE
Request new module: azure-vpn-gateway

### ISSUE THREAD

**Issue by sunmeher** [cloud-native-toolkit/software-everywhere#210]
**Related user story**
#74 

**Type of module**
terraform

**If requesting a terraform module, what is the target cloud platform?**
azure

**What is the purpose of the module?**
Create an Azure VPN gateway for point-to-point, remote employee and vnet-to-vnet connections.

**What is the category of the module?**
network

**Comment by rich-ehrhardt** [comment]
Module has been created
