### ISSUE TITLE
Request new module: module-global-pullsecret

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/software-everywhere#219]
**Related user story**
[Global Pull Secret module](https://github.com/cloud-native-toolkit/software-everywhere/issues/23)

**Type of module**
terraform 

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
This module does the following, as per the steps mentioned in https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=tasks-configuring-your-cluster-pull-images

1. Update global pull secret in openshift-config namespace
2. Reload/replace all worker nodes (one by one) for the changes to take effect.
3. Reattach the portworx storage and Restart the portworx service to each worker node.

**What is the category of the module?**
 infrastructure

**Comment by triceam** [comment]
This needs to be a `gitops` module b/c it will be applying changes to the cluster, not a plain `terraform` module.

**Comment by triceam** [comment]
We may be able to apply the global pull secret without reloading worker nodes:
![image](https://user-images.githubusercontent.com/974294/168793548-7d0b62b3-4967-4eac-b13f-1fe452521238.png)

Create a DaemonSet that modifies the file system of the node directly to update the pull secret.  Example DaemonSet here: https://github.com/cloud-native-toolkit/toolkit-charts/tree/main/stable/ocp-userspaces-daemonset

**Comment by triceam** [comment]
To manually test the pull secret on a cluster node:

1. `oc get nodes` to get a list of nodes
2. `oc debug node/{ip}` (get the ip from `oc get nodes`)
3. in the debug terminal `chroot /host`
4. look at existing docker config `cat .docker/config.json`
5 add the docker config:
  ```
  export IBM_ENTITLEMENT_KEY=<entitlement key>
  export IBM_ENTITLEMENT_USER=cp
  export IBM_ENTITLEMENT_SERVER=cp.icr.io
  
  PASSWD=`echo "${IBM_ENTITLEMENT_USER}:${IBM_ENTITLEMENT_KEY}" | tr -d '\n' | base64 -i -w 0`
  
  cp config.json config.json.backup
  cat config.json | jq '.auths += {"'$IBM_ENTITLEMENT_SERVER'":{"auth":"'$PASSWD'"}}' > config.json.tmp
  mv config.json.tmp config.json
  ```
6. Test that you can pull a CPD image that requires the auth key:
  ```
  crictl pull cp.icr.io/cp/cpd/zen-database-core@sha256:2c8e052b489fa1e60e993ddd11952896462107af4b394b1f002a0128efe79c7a
  ```

**Comment by triceam** [comment]
Manually pulling on the node will show a message like this:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/974294/169576459-e83d7fd1-460e-45c9-a36f-b6b3a817d7e2.png">

If you're not authenticated with the pull secret on the node, you'll see something like this:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/974294/169576636-65d038b4-df07-4750-b770-12f03c28ab39.png">
