### ISSUE TITLE
Tammy would like to entitle the entire OpenShift cluster to install/use Cloud Paks 

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#23]
Module to apply cluster-wide entitlement key

CP4D requires a cluster-wide entitlement key.  Currently we work around it by creating an image pull secret in the namespaces where CP4D components will be deployed.

MAS-ansible automation has a playbook that we can reference/lift logic from that applies the secret cluster-wide and reboots worker nodes.  module that does this, so we can have 1 operation that will be applied cluster-wide?
https://ibm-mas.github.io/ansible-devops/playbooks/cp4d/#hack-worker-nodes

Implementation here: https://github.com/ibm-mas/ansible-devops/tree/2df842bc255a1cf019233cc3e4c1f2f097716ec5/ibm/mas_devops/roles/cp4d_hack_worker_nodes

**Comment by smatthyssen** [comment]
Reference cloud-native-toolkit/terraform-gitops-pull-secret#17

**Comment by sgumpana** [comment]
For CPD the instructions are : https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=tasks-configuring-your-cluster-pull-images

**Comment by balasgit** [comment]
Based on the discussion with @sgumpana & @spansare , this is major blocker for DB2 which needs to resolved..

**Comment by balasgit** [comment]
the following script will help us address the issue as we need to explore something similar for replace worker nodes

- Script: https://github.com/mumutyal/px-utils/blob/master/px_vpc_upgrade/vpc_upgrade_util.sh
- Usage : ./vpc_upgrade_util.sh CLUSTER_NAME replace worker WORKER_ID_1 WORKER_ID_2 WORKER_ID_3 WORKER_ID_4
- Details : After ibmcloud login —sso, point to the account and then execute the above script

**Comment by sgumpana** [comment]
For global pull secret update on cluster level (openshift-config). We can avoid reattaching portworx storage  to worker nodes after reload/replace, with the below steps:

1. Create cluster
2. Configure global pull secret (CPD link: [Configuring the global image pull secret](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=tasks-configuring-your-cluster-pull-images#preinstall-cluster-setup__pull-secret))
3. Reload/Replace worker nodes
4. Then run portworx module.

With this we can skip reattaching portworx volumes.

**Comment by tcskill** [comment]
what i've been using to create global pull secret

```
oc extract secret/pull-secret -n openshift-config
if [ "$(cat .dockerconfigjson)" = "" ]; then
 echo "creating new .dockerconfigjson"
 oc create secret docker-registry --docker-server=cp.icr.io --docker-username=cp \
   --docker-password=$CPD_KEY --docker-email="fyre@us.ibm.com" -n openshift-config pull-secret
 oc extract secret/pull-secret -n openshift-config
fi
if [ "$(cat .dockerconfigjson | grep '.auths' | grep 'cp.icr.io')" = "" ]; then
 echo "updating .dockerconfigjson"
 sed -i -e 's|:{|:{"cp.icr.io":{"auth":"'$b64_credential'"\},|' .dockerconfigjson
fi
oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=./.dockerconfigjson
```

**Comment by balasgit** [comment]
As discussed in the iteration,

- We are going to manual replace worker nodes for ROKS. 
- This issue will be discussed with IBM ROKS OM and find resolution

**Comment by sgumpana** [comment]
I have raised a new module request for this automation (https://github.com/cloud-native-toolkit/software-everywhere/issues/219)
I am working on this.

**Comment by triceam** [comment]
@sgumpana I am reviewing your request now.  To be clear, all modules that are applying changes to a cluster need to be `gitops` type modules, not `terraform` type modules.   We won't always have access to apply changes directly, and the pattern that we have established is that all modules making changes to the cluster should be `gitops` modules.   We're even switching all the Portworx modules to `gitops`.

**Comment by triceam** [comment]
We may be able to apply the global pull secret without reloading worker nodes:
![image](https://user-images.githubusercontent.com/974294/168793548-7d0b62b3-4967-4eac-b13f-1fe452521238.png)

Create a DaemonSet that modifies the file system of the node directly to update the pull secret.  Example DaemonSet here: https://github.com/cloud-native-toolkit/toolkit-charts/tree/main/stable/ocp-userspaces-daemonset

**Comment by triceam** [comment]
Per discussion in office hours now: automatic reloading of nodes does not happen on OCP4.8 and later (our minimum version)

**Comment by triceam** [comment]
Created as a `gitops` module repo here:  https://github.com/cloud-native-toolkit/terraform-gitops-module-global-pullsecret

**Comment by triceam** [comment]
There will be 2 modules:
- https://github.com/cloud-native-toolkit/terraform-gitops-module-global-pullsecret will append to the global pull secret
- https://github.com/cloud-native-toolkit/terraform-gitops-global-pullsecret-synch will synchronize pull secrets across nodes, without requiring a restart
