### ISSUE TITLE
Request new module: azure-ocp-ipi

### ISSUE THREAD

**Issue by NoeSamaille** [cloud-native-toolkit/software-everywhere#24]
**Related user story**
[712](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/712)

**Type of module**
terraform

**If requesting a terraform module, what is the target cloud platform?**
azure

**What is the purpose of the module?**
Module to provision self-managed OpenShift via IPI/UPI on Azure

**What is the category of the module?**
cluster

**Comment by rich-ehrhardt** [comment]
Repo created and added to catalog.
