### ISSUE TITLE
Terraform Init - Error inside container 

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#250]
checked with couple of folks as they are not seeing this error.. Any workaround for this issue ?

<img width="1268" alt="Screen Shot 2022-06-02 at 2 20 29 PM" src="https://user-images.githubusercontent.com/25986944/171720677-1751228e-ae15-4130-ae44-9263f6db6cbb.png">

**Comment by triceam** [comment]
Do you mean the plugin cache message?  If so, that can be ignored.

**Comment by balasgit** [comment]
Yes thats correct.. Let me close issues.. thanks
