### ISSUE TITLE
Segmentation Fault when executing gitops setp in Colima

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#254]
│ Error: local-exec provisioner error
│ 
│   with module.gitops_repo.module.gitops-repo.null_resource.repo,
│   on .terraform/modules/gitops_repo.gitops-repo/main.tf line 28, in resource "null_resource" "repo":
│   28:   provisioner "local-exec" {
│ 
│ Error running command '.terraform/modules/gitops_repo.gitops-repo/scripts/create-repo.sh 'github.com'
│ 'balasgit' 'df--cp4d-gitops' 'false' 'kICclfm9YKxxCZZn' 'false'': exit status 139. Output:
│ .terraform/modules/gitops_repo.gitops-repo/scripts/create-repo.sh: line 48:   663 Segmentation fault
│ gitu exists "${REPO}" -o "${ORG}"
│ Creating repo: balasgit/df--cp4d-gitops 
│ .terraform/modules/gitops_repo.gitops-repo/scripts/create-repo.sh: line 48:   665 Segmentation fault
│ gitu create "${REPO}" -o "${ORG}" --public="${PUBLIC}" --autoInit="true"
│

**Comment by balasgit** [comment]
Workaround is to try with docker desktop which works fine

**Comment by triceam** [comment]
I'm now seeing a similar issue in colima:

```
 Error: External Program Execution Failed
│
│   with module.gitops_repo.module.gitops-repo.module.setup_clis.data.external.setup-binaries,
│   on .terraform/modules/gitops_repo.gitops-repo.setup_clis/main.tf line 22, in data "external" "setup-binaries":
│   22:   program = ["bash", "${path.module}/scripts/setup-binaries.sh"]
│
│ The data source received an unexpected error while attempting to execute the program.
│
│ Program: /bin/bash
│ Error Message: /workspaces/current/200-openshift-gitops/.terraform/modules/gitops_repo.gitops-repo.setup_clis/scripts/setup-binary.sh: line 74:  4532 Segmentation fault      "${BIN_DIR}/${CLI_NAME}" ${TEST_ARGS} > /dev/null 2>
│ /dev/null
│ Error downloading gitu
│
│ State: exit status 1
```

**Comment by triceam** [comment]
Colima is no longer officially supported per: https://github.com/cloud-native-toolkit/automation-solutions/blob/main/common-files/RUNTIMES.md
