### ISSUE TITLE
cp4d-instance instance is found in the catalog

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#28]
For some reason, gitops-cp4d-instance is not visible from the BOM even though the module exist in the Gitrepo. 

i have verified name with "module.cloudnativetoolkit.net" but BOM keeps throwing errors as shown below.

iascable build -i 500-telco-cp4d.yaml 
Name: gitops-telco-cloud-cp4d
Loading catalog from url: https://modules.cloudnativetoolkit.dev/index.yaml

Error: Unable to find module (undefined): **_gitops-cp4d-instance_**

**Comment by triceam** [comment]
Fixed
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/974294/167979646-d5e10d77-f994-4d97-888f-74eb5182fb39.png">
