### ISSUE TITLE
Request for New Cluster for CP4BA with 8 worker node and 16X32 

### ISSUE THREAD

**Issue by BrahmSingh** [cloud-native-toolkit/software-everywhere#350]
@triceam 

Request to you please create a new cluster for CP4BA. 
As per IKC (IBM Knowledge Center), we need a **minimum of 8 worker nodes with a 16x32 system required for CP4BA**.

https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=ppd-system-requirements

<img width="1089" alt="Screenshot 2022-07-26 at 6 35 17 PM" src="https://user-images.githubusercontent.com/103416270/181012950-4d12a61b-fc38-4f18-b48f-bce23b40b04a.png">

Thanks & Regards
Brahm Singh

**Comment by BrahmSingh** [comment]
FYI @saratrip

**Comment by BrahmSingh** [comment]
@triceam Did you get a chance to review the request?

**Comment by BrahmSingh** [comment]
Hi, @triceam can you please review the request and take the necessary action?

**Comment by triceam** [comment]
The `toolkit-dev-cp4ba-02` cluster is now available in the `Cloud-Native Squad 02` account.  This is an OpenShift 4.10 cluster, with 9x (16core x 32GB RAM) workers, and ODF deployed.  You should already have access to the cluster/

The cluster is available at:
[https://cloud.ibm.com/kubernetes/clusters/cbhvhnlw0v440t0n4mhg/overview?platformTyp[…]&region=us-east&resourceGroup=a3e53d10e43b46e6b3f2cbc8f01ee1eb](https://cloud.ibm.com/kubernetes/clusters/cbhvhnlw0v440t0n4mhg/overview?platformType=openshift&region=us-east&resourceGroup=a3e53d10e43b46e6b3f2cbc8f01ee1eb)

With the cluster dashboard at:
https://console-openshift-console.toolkit-dev-cp4ba-02-0ed2b1307d0ce0e0627ae949f443cd72-0000.us-east.containers.appdomain.cloud/
