### ISSUE TITLE
Request new module: terraform-ibm-ocp-proxyconfig

### ISSUE THREAD

**Issue by timroster** [cloud-native-toolkit/software-everywhere#353]
**Related user story**
related to https://github.com/cloud-native-toolkit/planning/issues/837, but operating at the cluster level. As a companion module for creating a proxy also https://github.com/IBM/automation-ibmcloud-infra-openshift/issues/3

**Type of module**
terraform 

**If requesting a terraform module, what is the target cloud platform?**
ibm
(may be extended with logic for other platforms depending on tasks to configure cluster properties)

**What is the purpose of the module?**
Companion module for modules that create HTTP/HTTPS proxies in infrastructure. Ex: https://github.com/cloud-native-toolkit/terraform-ibm-vsi-proxy

This module takes as input a squid endpoint ip/host and port and applies the configuration to ocp through the proxy resource. On IBM Cloud, the implementation does a reboot of all workers for additional updates to the crio configuration in the workers to be applied.

**What is the category of the module?**
infrastructure (cluster add-on)

**Source for module**
Once the module is created, https://github.com/timroster/terraform-ocp-proxyconfig will be tested and merged in

**Comment by timroster** [comment]
Repo created and populated here: https://github.com/cloud-native-toolkit/terraform-ocp-proxyconfig

**Comment by triceam** [comment]
Closing: not needed.
Repo deleted: https://github.com/cloud-native-toolkit/terraform-gitops-terraform-ibm-ocp-proxyconfig
Removed from catalog: https://github.com/cloud-native-toolkit/software-everywhere/commit/9765283816e33d7444400579cc87a8b346e1c32a
