### ISSUE TITLE
Tubnonomic automation no longer working properly

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#354]
The turbnomic automation fails to deploy on both OCP 4.8 and 4.10 on IBM Cloud.

Automation: https://github.com/IBM/automation-turbonomic

The deployment never becomes healthy b/c all of the PVCs (which use the storage class created by the 202 layer) never become healthy.

The error events coming from the PVCs are similar to:
```
Generated from vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_be0c2dbc-2418-4f0a-8069-3a17a2503793
6 times in the last 1 hour
(combined from similar events): failed to provision volume with StorageClass "ibmc-vpc-block-mzr": rpc error: code = InvalidArgument desc = {RequestID: 84bf2f91-8e7d-4c93-af0b-b22daff331e5 , Code: InvalidParameters, Description: Failed to extract parameters, BackendError: <sizeRange> is an invalid parameter, Action: Please provide valid parameters}
```

The storage class has a volume size 10-2000Gi.  The volumes have a size of 1Gi, so I suspect that is the issue.

![image.png](https://images.zenhubusercontent.com/5727947ebf93871ccd9a60b6/78f62cc4-050e-44c4-8f78-ae01edd40647)
![image.png](https://images.zenhubusercontent.com/5727947ebf93871ccd9a60b6/5e8e66c6-b92a-4ad4-8873-3c661d43512f)

**Comment by timroster** [comment]
is there any reason why the default storage (block) or maybe `ibmc-vpc-block-metro-10iops-tier` since wait for first customer is specified in https://github.com/turbonomic/t8c-install/wiki/Storage-Class-Requirements ?

**Comment by triceam** [comment]
I was able to recover the deployment by changing the storage class used by Turbonomic to the cluster default: `ibmc-vpc-block-10iops-tier`

Before changing the automation, I need to understand why we created that storage class in the first place... and I do not know why.   @tcskill @mjperrins @seansund Any idea why we create the `ibmc-vpc-block-mzr` storage class for IBM Cloud deployments?  This is what is causing turbo to fail.

**Comment by tcskill** [comment]
@triceam yes. That is needed on ibm cloud only when you have a vpc deployment or multi region deployment because by default Ibm cloud creates block storage with bind immediately and need it to be wait for first consumer (note only for the use case described above) when on classic cluster not needed, also when on single zone not needed

**Comment by timroster** [comment]
standard metro classes will work for this use case, no need for a custom storageclass

**Comment by triceam** [comment]
OK, well, it doesn't work anymore.  The `<sizeRange> is an invalid parameter, Action: Please provide valid parameters}` error is b/c turbo is requesting 1Gi volumes, and the minimum size is 10Gi.  I will update our automation to use the metro class.

**Comment by tcskill** [comment]
Yes I see new metro has wait for first consumer so should work fine

**Comment by triceam** [comment]
Removed 202 layer (no custom storage class for IBM Cloud, switched to use `ibmc-vpc-block-metro-10iops-tier` storage class on IBM Cloud.  

Fixed in:
- https://github.com/cloud-native-toolkit/automation-solutions/pull/191/
- https://github.com/IBM/automation-turbonomic/pull/17
