### ISSUE TITLE
Issue on Ascent: {issue}

### ISSUE THREAD

**Issue by jlang027** [cloud-native-toolkit/software-everywhere#423]
**Describe the bug**

**To Reproduce**
1. Go to 'https://builder.techzone-automation.com/mapping'

4. See error: IBM_CLOUD_FS_BP_0_4_0 still shown in the SCC Profile column

**Expected behavior**
please update to the most recent SCC Profile "IBM Cloud for Financial Services v0.5.0"

**Screenshots**
![image](https://user-images.githubusercontent.com/38346737/186157081-66b4c058-d3f2-4bff-81a9-8ccc5a3bb568.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome

**Comment by NoeSamaille** [comment]
Hi @jlang027 thanks for raising this it has now been addressed.
