### ISSUE TITLE
VPE Gateway migration error - Namespace issues 

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#464]
More details on test https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpe-gateway/runs/8121977251?check_suite_focus=true

(A) Namespace 
(B) Error on Resource group

╷
│ Error: local-exec provisioner error
│ 
│   with module.icr.null_resource.create_registry_namespace,
│   on .terraform/modules/icr/main.tf line 34, in resource "null_resource" "create_registry_namespace":
│   34:   provisioner "local-exec" {
│ 
│ Error running command
│ '.terraform/modules/icr/scripts/create-registry-namespace.sh 'eu-gb'
│ 'vpc-count-rg' 'uk-south' 'vpc-count-rg' 'true'': exit status 1. Output:
│ The region is set to 'uk-south', the registry is 'uk.icr.io'.
│ 
│ OK
│ Checking registry namespace: vpc-count-rg
│ Registry namespace vpc-count-rg not found, creating it.
│ Adding namespace 'vpc-count-rg' in resource group 'vpc-count-rg' for
│ account GoldenEye GoldenEye Development's Account in registry uk.icr.io...
│ 
│ FAILED
│ The requested namespace is already in use in registry 'uk.icr.io'.
│ Choose a different namespace.

**Comment by seansund** [comment]
The value provided for the registry namespace already exists (likely colliding with the one in our Cloud Native Squad account). Change the name of the registry namespace used for the test.

**Comment by balasgit** [comment]
Addressed and re-ran which gives following error - https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpe-gateway/runs/8141882753?check_suite_focus=true

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
╷
│ Error: Cycle: module.resource_group.null_resource.resource_group, module.resource_group.null_resource.volumes, module.resource_group.var.resource_group_name (expand), module.resource_group.output.name (expand)
│ 
│

**Comment by seansund** [comment]
You've somehow created a circular reference between the modules

**Comment by balasgit** [comment]
Resolved this but running into VPN unique name issues

Tried passing default values but not sure where that VPC_count7 hardcoded coming
