### ISSUE TITLE
VPC Subnet Migration module Error 

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#465]
More details - https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-subnets/runs/8122679880?check_suite_focus=true

Error: [0m Error: [ERROR] Error while creating VPC {
│     "Message": "Provided Name (vpc-count7-vpc) is not unique",
│     "StatusCode": 400,
│     "Result": {
│         "errors": [
│             {
│                 "code": "validation_unique_failed",
│                 "message": "Provided Name (vpc-count7-vpc) is not unique",
│                 "target": {
│                     "name": "name",
│                     "type": "field",
│                     "value": "vpc-count7-vpc"
│                 }
│             }
│         ],
│         "trace": "38d124a4-6bca-4baf-8c27-b9430c16fbf5"
│     }
│ }
│  
│ 
│   with module.vpc.ibm_is_vpc.vpc[0],
│   on .terraform/modules/vpc/main.tf line 33, in resource "ibm_is_vpc" "vpc":
│   33: resource ibm_is_vpc vpc {
│ 
╵
Error: Process completed with exit code 1

**Comment by seansund** [comment]
Same problem/solution as - https://github.com/cloud-native-toolkit/software-everywhere/issues/475

(It is also very likely this repo's test is the one that caused the conflict with the other one)

**Comment by balasgit** [comment]
Thanks Sean - it worked.
