### ISSUE TITLE
VPC Flow log migration - Test error - ID not found

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#469]
VPC id not found: ocp4-latest-vpc
Validation failed
Error: Process completed with exit code 1.

More details about this test - https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-flow-log/runs/8123260057?check_suite_focus=true

**Comment by seansund** [comment]
The environment does not have the clis available to run the test, particularly the `ibmcloud` cli. Add this block to the stage0.tf file:

```hcl
module setup_test_clis {
  source = "github.com/cloud-native-toolkit/terraform-util-clis.git"

  bin_dir = "${path.cwd}/test_bin_dir"
  clis = ["kubectl", "oc"]
}

resource local_file bin_dir {
  filename = "${path.cwd}/.bin_dir"

  content = module.setup_test_clis.bin_dir
}
```

and add these lines to the top of validate-deploy.sh:

```shell
BIN_DIR=$(cat .bin_dir)

export PATH="${BIN_DIR}:${PATH}"
```

**Comment by balasgit** [comment]
Thanks Sean.  Still the same issue with recommendations. 

I also tried switching to CLI-tools:v1.1 image instead of terraformv1.1 but same error.

**Comment by balasgit** [comment]
Switched to IBMCloud CLI which helped the issues to be addressed
