### ISSUE TITLE
VPC LB module - build error

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#471]
More details abt the build error - https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-load-balancer/actions

│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "kms_key_name" but a
╷
│ Error: Unsupported argument
│ 
│   on stage1-vpc.tf line 4, in module "vpc":
│    4:   resource_group_id   = module.resource_group.id
│

**Comment by seansund** [comment]
The inputs to the vpc module in the test need to be updated to match the latest. Particularly, `resource_group_id = module.resource_group.id` needs to be replaced with `resource_group_name = module.resource_group.name`

**Comment by balasgit** [comment]
updated all the 3 testcases with the resource name instead of id as well as added APIKey since compile errors shows one after other during the testing instead of showing everything.
