### ISSUE TITLE
VPC SSH Module - Build Error

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#473]
│ Error: Missing required argument
│ 
│   on stage1-resource-group.tf line 1, in module "resource_group":
│    1: module "resource_group" {
│ 
│ The argument "ibmcloud_api_key" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│ 
│   on stage1-resource-group.tf line 5, in module "resource_group":
│    5:   provision           = false
│ 
│ An argument named "provision" is not expected here.
╵
╷
│ Warning: Value for undeclared variable

More Details

https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-ssh/runs/8122601129?check_suite_focus=true

**Comment by seansund** [comment]
The inputs to the resource group test module need to be updated to the match the latest. Remove the `provision` variable and add the `ibmcloud_api_key` variable

**Comment by balasgit** [comment]
Addressed and build is success

**Comment by balasgit** [comment]
**Publication is failing**

https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-ssh/actions

Run cloud-native-toolkit/action-repository-dispatch@main
Creating released respository dispatch for cloud-native-toolkit/garage-terraform-modules
  client_payload: {"repo":"terraform-ibm-modules/terraform-ibm-toolkit-vpc-ssh","ref":"refs/tags/v[1](https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-ssh/runs/8141174361?check_suite_focus=true#step:2:1).[7](https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-ssh/runs/8141174361?check_suite_focus=true#step:2:8).2","sha":"3e45f45555af[8](https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-ssh/runs/8141174361?check_suite_focus=true#step:2:9)d07f84c68a5[9](https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vpc-ssh/runs/8141174361?check_suite_focus=true#step:2:10)b3b1c71b2d1dedc"}
Error: **Repository not found OR token does not have sufficient permission**
