### ISSUE TITLE
VSI Bastion Module - Build Error

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#475]
Error: [0m Error: [ERROR] Error while creating VPC {
│     "Message": "Provided Name (vpc-count7-vpc) is not unique",
│     "StatusCode": 400,
│     "Result": {
│         "errors": [
│             {
│                 "code": "validation_unique_failed",
│                 "message": "Provided Name (vpc-count7-vpc) is not unique",
│                 "target": {
│                     "name": "name",
│                     "type": "field",
│                     "value": "vpc-count7-vpc"
│                 }
│             }
│         ],
│         "trace": "7a8d5bab-21ee-474f-8549-dc865e55d337"
│     }
│ }
│  
│ 
│   with module.vpc.ibm_is_vpc.vpc[0],
│   on .terraform/modules/vpc/main.tf line 33, in resource "ibm_is_vpc" "vpc":
│   33: resource ibm_is_vpc vpc {
│ 
╵
Error: Process completed with exit code 1.

More Details - https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-vsi-bastion/runs/8138204552?check_suite_focus=true

**Comment by seansund** [comment]
@balasgit "Provided name is not unique" means another test case is running that is using the same name for the VPC (probably defined in the test case).

The simplest way to fix it is to generate a random, unique name for the VPC in each test using the [random string](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string) Terraform resource

**Comment by balasgit** [comment]
Check-image.sh is not there 

Error: local-exec provisioner error
│ 
│   with module.bastion.module.vsi-instance.null_resource.print_deprecated,
│   on .terraform/modules/bastion.vsi-instance/main.tf line 58, in resource "null_resource" "print_deprecated":
│   58:   provisioner "local-exec" {
│ 
│ Error running command
│ '.terraform/modules/bastion.vsi-instance/scripts/check-image.sh
│ 'deprecated' 'ibm-ubuntu-18-04-6-minimal-amd64-2' 'false'': exit status 1.
│ Output: Error: ibm-ubuntu-18-04-6-minimal-amd64-2 image is
│ deprecated
│

**Comment by balasgit** [comment]
Build error after updating image

Error: [0m Error: [ERROR] Error while creating VPC {
│     "Message": "Provided Name (vpc-count7-vpc) is not unique",
│     "StatusCode": 400,
│     "Result": {
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│         "errors": [

**Comment by balasgit** [comment]
Fixed the image issues
