### ISSUE TITLE
Failed to create solution with default user identify, ie no roles defined in AppID

### ISSUE THREAD

**Issue by mjperrins** [cloud-native-toolkit/software-everywhere#476]
If you try and create a solution as if you are a default user , ie logged into Ascent with no defined roles. Get an error saying I need Editor identity. All users should be able to create solutions using the wizard

The default user should not be forced to have Editor role in App ID

![Screen Shot 2022-09-04 at 10.48.35 AM.png](https://images.zenhubusercontent.com/570fff13bf93871ccd99764f/f45e99eb-0b4b-4b8f-b4ea-a2857f8dcc17
)

**Comment by NoeSamaille** [comment]
Fixed
