### ISSUE TITLE
Maximo Application Suite TechZone ATK Collection--https://techzone.ibm.com/collection/maximo-application-suite-automation-for-multicloud

### ISSUE THREAD

**Issue by yr2022** [cloud-native-toolkit/software-everywhere#525]
This issue refers to the Automation of Maximo Application Suite (MAS) and its collection on Tech Zone for driving consumption. The readiness of the assets aligned to See It, Learn It, Do It and Resources journey is under review by Matt for final sign off. Post review we will upload the video's to YouTube channel to back link it in the Tech Zone collection. https://techzone.ibm.com/collection/maximo-application-suite-automation-for-multicloud

Business Value
See It

    Videos
    Hero Stories
    Documentation
    Seismic Reference

Learn It

    Videos
    Documentation
    Training
    Demos

Do It

    Product Videos
    Sandbox Collection
    ROKS Cluster Request

Resources

    Analyst Report
    Installation Guide
    Documentation

**Comment by yr2022** [comment]
Videos approved by Matt, uploaded on YouTube channel. Tech Zone collection release date need to be determined once Matt has reviewed content.

**Comment by seansund** [comment]
blocked by #363

**Comment by yr2022** [comment]
All issues have been resolved and MAS collection for Ansible approach has been released on TechZone.  Link: https://techzone.ibm.com/collection/maximo-application-suite-automation-for-multicloud
