### ISSUE TITLE
gitops-cp-ace-dashboard not showing up in the catalog

### ISSUE THREAD

**Issue by gowdhaman-j** [cloud-native-toolkit/software-everywhere#58]
In software-everywhere application https://modules.cloudnativetoolkit.dev/
"gitops-cp-ace-dashboard" module (https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-dashboard/actions) is not listed even after after successful test.

**Comment by triceam** [comment]
Added to module catalog

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/974294/159775735-51d0711c-a1da-4775-970c-23b2d7f0e1e3.png">
